spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

druid:
  dbType: mysql
  stat-filter:
    mergeSql: true
    slowSqlMillis: 10000
    logSlowSql: true
  wall-filter:
    dir: META-INF/druid/wall/mysql
    limitZeroAllow: true
    multiStatementAllow: true
    metadataAllow: false
    wrapAllow: false

mybatis:
  mapper-locations: classpath:com/zjh/mybatis/**/dao/*.xml
  type-aliases-package: com.zjh.mybatis.**.model.*

logging:
  config: classpath:logback/logback.xml
#  path: D:/logs/message-monitor